### ISSUE TITLE
Update OpenCore to 0.8.6 w/ macOS Ventura fixes

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#10]
(Latest update): https://dortania.github.io/hackintosh/updates/2022/11/07/acidanthera-november.html

**Comment by Qonfused** [comment]
https://dortania.github.io/hackintosh/updates/2022/11/07/acidanthera-november.html

**Comment by Qonfused** [comment]
TODO:
- [ ] **Remove CPUFriend** - i7 10510u and i5 10210u CPUs have native CPU power management on macOS.
- [ ] **Tune config for Apple GuC Firmware (`-igfxfw` boot arg)**

**Comment by Qonfused** [comment]
Base OpenCore files w/ [prebuilt ACPI patches](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-prebuilt.html#laptop-coffee-and-comet-lake-9th-and-10th-gen):
![Screen Shot 2022-11-22 at 4 20 35 PM](https://user-images.githubusercontent.com/32466081/203433097-8c5d41d6-e9bf-4540-909b-c3db21dbcef8.png)

Additional Files:
Folder | File | URL
--- | --- | ---
`OC/Drivers` | HfsPlus | [`HfsPlus.efi`](https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlus.efi)

**Comment by Qonfused** [comment]
Removed IMEI ACPI patch quirks
![image](https://user-images.githubusercontent.com/32466081/203483859-d724ee9a-ad86-4a3b-ba33-891b38eed7eb.png)

**Comment by Qonfused** [comment]
Will need to do a OC clean snapshot in propertree; was using an older version of propertree without 0.8.6 serials/etc.

**Comment by Qonfused** [comment]
Currently investigating a kernel panic around `Booter > Quirks`:
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-panic-on-invalid-frame-pointer

**Comment by Qonfused** [comment]
Working on updating kexts, but I'm able to get HDMI working so far after updating Lilu & WhateverGreen w/ the updated config.

**Comment by UsedDiscord** [comment]
> Working on updating kexts, but I'm able to get HDMI working so far after updating Lilu & WhateverGreen w/ the updated config.

Hey! Good to see you again @Qonfused  :)
Sorry for not participating too much in the bug search ^^' I'm studying Law (History of administration, what a bore...), and literally, it takes me DAY AND NIGHT, Weekend included...

I've been trying to figure out the whole conversation, so for now, the Screenpad is still "buggy", but now, the HDMI connection would work on the INTEL? chip (I'm talking about Intel because Nvidia is not supported...?) on an external monitor without any difficulty? that would be awesome to hear!
Is that right?

UsedDiscord / Magik (my new pseudo as well)

**Comment by Qonfused** [comment]
Yeah that's correct. I also noticed that both trackpad buttons also work but are mapped to the wrong functions (can be fixed).

**Comment by UsedDiscord** [comment]
Yeah, that's good news! 
Concerning the trackpad, I had noticed that, but is it true? or did I use my trackpad wrong? It's up to you to check it too, so I don't say anything stupid...

**Comment by Qonfused** [comment]
There were some additional plugins that needed to be imported from the voodoo kexts that weren't explicitly imported after doing a propertree clean snapshot; this may have affected this behavior since beforehand I noticed the same behavior as you (right click button not working).

As long as both buttons function it shouldn't be difficult to fix.

**Comment by UsedDiscord** [comment]
Indeed, it tells me something about this story of snapshot...

**Comment by Qonfused** [comment]
A lame fix would be to use [karabiner](https://karabiner-elements.pqrs.org/), which works but adds unnecessary additional work for people to do.

**Comment by UsedDiscord** [comment]
Exactly, [https://karabiner-elements.pqrs.org/docs/help/how-to/mouse-button/](Karabiner Doc Mouse Button) but for a first preview, that is good i think, so i think try that when i have the time...
