### ISSUE TITLE
Fix VoodooI2CHID issue w/ Touchscreen

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#12]
On startup, touchscreen on both displays works in legacy mouse mode (no multitouch/PTP mode); it also appears to no longer respond about a minute after login. These issues were also described in @shiecldk's [tonymacx86 UX582 thread](https://www.tonymacx86.com/threads/voodooi2c-help-and-support.243378/page-144) prior to resolution, and describes an issue with VoodooI2CHID where changing driver/device priority can break multitouch.

@gkvt's fork of VoodooI2C at https://github.com/gvkt/VoodooI2CHID resolves an architecture incompatibility w/ multi-I2C HID devices; the workaround allows for greater control of which driver is attached to which device. The pull request for this fork was tracked in https://github.com/VoodooI2C/VoodooI2CHID/pull/58 (closed) and https://github.com/VoodooI2C/VoodooI2CHID/pull/59 (merged).

Refer to https://github.com/VoodooI2C/VoodooI2C/issues/485#issuecomment-968115898 for Info.plist changes (changes are to match drivers to device-specific product ids rather than device names).

For reference, [discussion on multi-touch support for touchscreen w/ VoodooI2C](https://github.com/VoodooI2C/VoodooI2C/issues/474#issuecomment-979154995) details the debugging used to modify the kext's Info.plist to prevent interference from touchscreen/precision trackpad event drivers.

**Comment by Qonfused** [comment]
Will need to verify that the I2C/etc paths are the same (and update the README); if these are the same then this fix should work OOB.

**Comment by Qonfused** [comment]
Found an explanation for the `VoodooI2CHID-AsTouchscreen.kext` and `VoodooI2CHID-AsTrackpad.kext` kexts [here](https://www.tonymacx86.com/threads/guide-asus-zenbook-pro-duo-15-oled-ux582-opencore.315661/post-2301364).

**Comment by Qonfused** [comment]
For the UX582:
Device | Identifier | ACPI Path | Vendor Id | Product Id
--- | --- | --- | --- | ---
Trackpad | `ELAN1406` | `_SB.PCI0.I2C1.ETPD` | `04F3` | `3101`
Primary Display | `ELAN9008` | `_SB.PCI0.I2C1.TPL0` | `04F3` | `2C56`
Screenpad Plus | `ELAN9009` | `_SB.PCI0.I2C1.TPL1` | `04F3` | `2C23`

For the UX481(FL):
Device | Identifier | ACPI Path | Vendor Id | Product Id
--- | --- | --- | --- | ---
Trackpad | `ELAN1207` | `_SB.PCI0.I2C1.ETPD` | `04F3` | `?`
Primary Display | `ELAN9008` | `_SB.PCI0.I2C0.TPL1` | `04F3` | `?`
Screenpad Plus | `ELAN9009` | `_SB.PCI0.I2C3.TPL0` | `04F3` | `?`

**Comment by UsedDiscord** [comment]
Indeed, the ACPI Patch are different from one model to another

**Comment by Qonfused** [comment]
There may be variations even within the same model (e.g. from different manufacturing runs). You'll need to verify that these values are the same; it's possible for the product id to vary even with everything else matching.

You can search for `VoodooI2C` in [IORegistryExplorer](https://github.com/vulgo/IORegistryExplorer) to find these devices:
![image](https://user-images.githubusercontent.com/32466081/204476516-0ed65596-7c78-46e3-bf2b-1713dce0267c.png)

You can find the vendor and product IDs as properties of `VoodooI2CHIDDevice` under each device. Note that the top of each substree (in grey) also shows the ACPI path after `_SB.PCI0`.

**Comment by Qonfused** [comment]
I suspect that the ACPI path for the UX481FA model may be different from the UX481FL one (left is FL model; right is FA model):
![Screenshot 2022-11-29 at 2 36 54 AM](https://user-images.githubusercontent.com/32466081/204479693-08b53a89-84ea-4566-8249-fbbf5d5ecd52.png)
The firmware on the right is from @wern-apfel, which appears to be missing the `ELAN9008` device for the primary display.

**Comment by UsedDiscord** [comment]
I'm on MacOS and i check on IORegistry :
 
 --> For TLP1 : 
![Capture d’écran 2022-11-29 à 11 26 28](https://user-images.githubusercontent.com/57113628/204506739-1414f116-1b0d-4bc3-81bf-b4dd103c7148.png)

--> For ETPD : 
![Capture d’écran 2022-11-29 à 11 36 09](https://user-images.githubusercontent.com/57113628/204507030-b17f678d-9c40-46b4-8b5c-662657f2c505.png)

--> And for TLP0 : 
![Capture d’écran 2022-11-29 à 11 37 03](https://user-images.githubusercontent.com/57113628/204507222-fe6f2d69-57a5-44d1-a881-2700c0fbca09.png)

By the way, i'have see something, if we click on TLP1, ETPD and TLP0, in ACP-Device it's say : "IOACPIPlatformDevice is not serializable" 

> For the UX481(FL):
> 
> Device	Identifier	ACPI Path	VID:PID
> Trackpad	`ELAN1207`	`_SB.PCI0.I2C1.ETPD`	`04F3:310E`
> Primary Display	`ELAN9008`	`_SB.PCI0.I2C0.TPL1`	`04F3:2B6A`
> Screenpad Plus	`ELAN9009`	`_SB.PCI0.I2C3.TPL0`	`04F3:29DE`

I confirm that for UX481FA.

**Comment by UsedDiscord** [comment]
> I suspect that the ACPI path for the UX481FA model may be different from the UX481FL one (left is FL model; right is FA model): ![Screenshot 2022-11-29 at 2 36 54 AM](https://user-images.githubusercontent.com/32466081/204479693-08b53a89-84ea-4566-8249-fbbf5d5ecd52.png) The firmware on the right is from @wern-apfel, which appears to be missing the `ELAN9008` device for the primary display.

To export the DSDT, can we do it from Windows or must we do it from MacOS? I have a memory lapse...

**Comment by Qonfused** [comment]
> > For the UX481(FL):
> > Device | Identifier | ACPI Path | VID:PID
> > --- | --- | --- | ---
> > Trackpad | `ELAN1207` | `_SB.PCI0.I2C1.ETPD` | `04F3:310E`
> > Primary Display | `ELAN9008` | `_SB.PCI0.I2C0.TPL1` | `04F3:2B6A`
> > Screenpad Plus | `ELAN9009` | `_SB.PCI0.I2C3.TPL0` | `04F3:29DE`
> 
> I confirm that for UX481FA.

I'd note that your screenpad's product id is `2C58`.

> To export the DSDT, can we do it from Windows or must we do it from MacOS? I have a memory lapse...

The easiest way would be on Windows/Linux with SSDTTime (you can find instructions [here](https://dortania.github.io/Getting-Started-With-ACPI/Manual/dump.html#from-windows)).

**Comment by UsedDiscord** [comment]
I think that the product id does not change much... but yes, small error... Regarding DSDT, I will dump is compared as well. Thanks for the reminder.Le 29 nov. 2022 14:59, Cory Bennett ***@***.***> a écrit :


For the UX481(FL):
DeviceIdentifierACPI PathVID:PIDTrackpadELAN1207_SB.PCI0.I2C1.ETPD04F3:310EPrimary DisplayELAN9008_SB.PCI0.I2C0.TPL104F3:2B6AScreenpad PlusELAN9009_SB.PCI0.I2C3.TPL004F3:29DE

I confirm that for UX481FA.

I'd note that your screenpad's product id is 2C58.

To export the DSDT, can we do it from Windows or must we do it from MacOS? I have a memory lapse...

The easiest way would be on Windows/Linux with SSDTTime (you can find instructions here).

**Comment by Qonfused** [comment]
> Refer to [VoodooI2C/VoodooI2C#485 (comment)](https://github.com/VoodooI2C/VoodooI2C/issues/485#issuecomment-968115898) for Info.plist changes (changes are to match drivers to device-specific product ids).

^^ The current workaround for this issue does require the specific product ids, though I suspect that every other value will be the same if there are any other devices with a different vendor id. If it has the same guid/uuid or pciid (should be evident somewhere in the DSDT), it's possible there's a better way of matching to the device than using the product id.

**Comment by Qonfused** [comment]
Also related is https://github.com/VoodooI2C/VoodooI2C/issues/321 for the trackpad freezing issue.

**Comment by Qonfused** [comment]
An updated table reflecting https://github.com/VoodooI2C/VoodooI2C/issues/474#issuecomment-992006331.
The 'Voodoo Satellite Drivers/Interfaces' correspond to what should show up in IORegistryExplorer under each device.
<table>
  <thead>
      <tr>
          <th>Device</th>
          <th>ACPI Path</th>
          <th>Vendor Id (VID)</th>
          <th>Product Id (PID)</th>
          <th>Voodoo Satellite Drivers/Interfaces</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=2><code>ELAN1207</code></td>
            <td rowspan=2><code>_SB.PCI0.I2C1.ETPD</code></td>
            <td rowspan=6><code>04F3</code></td>
            <td rowspan=2><code>310E</code></td>
            <td>VoodooI2CPrecisionTouchpadHIDEventDriver</td>
        </tr>
        <tr>
            <td>VoodooI2CMultitouchInterface</td>
        </tr>
        <tr>
            <td rowspan=2><code>ELAN9008</code></td>
            <td rowspan=2><code>_SB.PCI0.I2C0.TPL1</code></td>
            <td rowspan=2><code>2B6A</code></td>
            <td>VoodooI2CTouchscreenHIDEventDriver</td>
        </tr>
        <tr>
            <td>VoodooI2CMultitouchInterface</td>
        </tr>
        <tr>
            <td rowspan=2><code>ELAN9009</code></td>
            <td rowspan=2><code>_SB.PCI0.I2C3.TPL0</code></td>
            <td rowspan=2><code>29DE</code></td>
            <td>VoodooI2CTouchscreenHIDEventDriver</td>
        </tr>
        <tr>
            <td>VoodooI2CMultitouchInterface</td>
        </tr>
    </tbody>
</table>

**Comment by Qonfused** [comment]
Here's another way of checking for these values in macOS:
```bash
ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
```

Example:
```bash
$ ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1

>>>      +-o PCI0@0  
>>>          +-o I2C0@15  
>>>                  +-o TPL1  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x2b6a
>>>                        +-o VoodooI2CTouchscreenHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface  
>>>      +-o PCI0@0  
>>>          +-o I2C1@15,1  
>>>                  +-o ETPD  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x310e
>>>                        +-o VoodooI2CPrecisionTouchpadHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface  
>>>      +-o PCI0@0  
>>>          +-o I2C3@15,3  
>>>                  +-o TPL0  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x29de
>>>                        +-o VoodooI2CTouchscreenHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface
```

**Comment by Qonfused** [comment]
Here's another way of checking for these values in macOS:
```bash
ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
```

Example output:
```bash
$ ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
>>>      +-o PCI0@0  
>>>          +-o I2C0@15  
>>>                  +-o TPL1  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x2b6a
>>>                        +-o VoodooI2CTouchscreenHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface  
>>>      +-o PCI0@0  
>>>          +-o I2C1@15,1  
>>>                  +-o ETPD  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x310e
>>>                        +-o VoodooI2CPrecisionTouchpadHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface  
>>>      +-o PCI0@0  
>>>          +-o I2C3@15,3  
>>>                  +-o TPL0  
>>>                        |   "VendorID" = 0x4f3
>>>                        |   "ProductID" = 0x29de
>>>                        +-o VoodooI2CTouchscreenHIDEventDriver  
>>>                          +-o VoodooI2CMultitouchInterface
```

For checking just product ids:
```bash
$ ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" | grep ProductID | cut -d "=" -f2
>>> 0x2b6a
>>> 0x310e
>>> 0x29de
```

For checking for a specific device name:
```bash
$ ioreg -rxn ETPD -k i2cAddress -d1 | grep IOName | cut -d "=" -f2 
>>> "ELAN1207"
$ ioreg -rxn TPL1 -k i2cAddress -d1 | grep IOName | cut -d "=" -f2 
>>> "ELAN9008"
$ ioreg -rxn TPL0 -k i2cAddress -d1 | grep IOName | cut -d "=" -f2 
>>> "ELAN9009"

**Comment by Qonfused** [comment]
Interesting, was just testing using the same VoodooI2CHID kext as from the original repo (applying the new fixes in the info.plist) and found the main touchscreen gestures work.

**Comment by Qonfused** [comment]
Still stops working after a while; is fine for a little white after wake again.

**Comment by Qonfused** [comment]
Will need to check https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/commit/0b6711556207d49135466101fb8e217ab68704dd for any regressions (and after updating Voodoo kexts back to latest).

**Comment by Qonfused** [comment]
May require GPIO pinning or a similar DSDT patch:
https://github.com/VoodooI2C/VoodooI2C/issues/171

**Comment by Qonfused** [comment]
Some additional docs for APIC/GPIO for fixing trackpad polling collision:
https://github.com/5T33Z0/OC-Little-Translated/tree/main/05_Laptop-specific_Patches/Trackpad_Patches#instructions

**Comment by Qonfused** [comment]
Was able to confirm that trackpad polling is indeed causing a collision with touchscreen.
This issue will close w/ GPIO pinning for the trackpad in #19.

**Comment by Qonfused** [comment]
GPIO pinning doesn't appear to work for only the screenpad.
Here is the full implementation tested for reference:

```dsl
// SSDT-GPIO.aml
DefinitionBlock ("", "SSDT", 2, "UX481", "GPI0", 0x00000000)
{
    External (_SB_.PCI0.I2C0.TPL1, DeviceObj)
    External (_SB_.PCI0.I2C0.TPL1.SADR, FieldUnitObj)
    External (_SB_.PCI0.I2C0.TPL1.XCRS, MethodObj)
    External (_SB_.PCI0.I2C1.ETPD, DeviceObj)
    External (_SB_.PCI0.I2C1.ETPD.XCRS, MethodObj)
    External (_SB_.PCI0.I2C3.TPL0, DeviceObj)
    External (_SB_.PCI0.I2C3.TPL0.SADR, FieldUnitObj)
    External (_SB_.PCI0.I2C3.TPL0.XCRS, MethodObj)
    External (GPHD, FieldUnitObj)
    External (MTLI, FieldUnitObj)
    External (TPLI, FieldUnitObj)

    Scope (\)
    {
        If (_OSI ("Darwin")) { GPHD = Zero }
    }

    Scope (_SB.PCI0.I2C0.TPL1)
    {
        Method (_CRS, 0, Serialized)
        {
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x0010, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C0",
                    0x00, ResourceConsumer, _Y39, Exclusive,)
            })
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,)
                    { 0x0056 }
            })
            If (_OSI ("Darwin"))
            {
                CreateWordField (SBFB, \_SB.PCI0.I2C0.TPL1._CRS._Y39._ADR, ADR1)
                ADR1 = DerefOf (SADR [MTLI])
                Return (ConcatenateResTemplate (SBFB, SBFG))
            }
            Else { Return (XCRS ()) }
        }
    }

    Scope (_SB.PCI0.I2C1.ETPD)
    {
        Method (_CRS, 0, Serialized)
        {
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x0015, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C1",
                    0x00, ResourceConsumer, , Exclusive,)
            })
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,)
                    { 0x0051 }
            })
            If (_OSI ("Darwin"))
            {
                Return (ConcatenateResTemplate (SBFB, SBFG))
            }
            Else { Return (XCRS ()) }
        }
    }

    Scope (_SB.PCI0.I2C3.TPL0)
    {
        Method (_CRS, 0, Serialized)
        {
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x0010, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C3",
                    0x00, ResourceConsumer, _Y38, Exclusive,)
            })
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,)
                    { 0x002B }
            })
            If (_OSI ("Darwin"))
            {
                CreateWordField (SBFB, \_SB.PCI0.I2C3.TPL0._CRS._Y38._ADR, ADR1)
                ADR1 = DerefOf (SADR [TPLI])
                Return (ConcatenateResTemplate (SBFB, SBFG))
            }
            Else { Return (XCRS ()) }
        }
    }
}
```

**Comment by Qonfused** [comment]
GPIO pinning doesn't appear to work for only the screenpad. Will revert from https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/pull/19/commits/08c21be6bd6056c278924dc1da04147b614b62a8 to use polling instead (trackpad and primary display are GPIO pinned).

**Comment by Qonfused** [comment]
Will re-open for regression testing but close again on PR #19 merge.

**Comment by Qonfused** [comment]
Added documentation for the fix in this repo's wiki under [VoodooI2CHID-Workaround](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/wiki/VoodooI2CHID-Workaround).

**Comment by shiecldk** [comment]
> 

@Qonfused Do you still have the Trackpad freezing issue with VoodooI2C 2.7.1?

**Comment by Qonfused** [comment]
@shiecldk I'm looking into it in #24, though that may be a separate cause for touchscreen intermittency.
