### ISSUE TITLE
Update OpenCore 0.8.6 > 0.8.7 - Update Kexts 

### ISSUE THREAD

**Issue by UsedDiscord** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#13]
Hello,

I put a small list of Kexts that need to be updated.
As I don't have the permission for Pull Requests, I put it in an Issue.

What ChangeLog :

**Main changes** :
- Removed unwanted flicker when launching non-text entry.

- Changed macrecovery to download files into com.apple.recovery.boot by default.

- Improved Apple builtin picker (BootKicker.efi) on some systems and after reboot.

- ~Misc -> Boot -> ShowPicker changed from Boolean to String, valid values are:~

- - ~Always - Always show picker (equivalent to ShowPicker=True).~

- - ~Never - Never show picker (equivalent to ShowPicker=False).~

- - ~SkipOnHibernateWake - Don't show picker if waking from macOS hibernation.~

- Misc -> Boot -> added HibernateSkipsPicker (Boolean): not to show picker if waking from macOS hibernation. Failsafe value: false.

**config.plist** : 
- ~Misc -> Boot -> ShowPicker changed from Boolean to String, valid values are Always, Never and SkipOnHibernateWake.~
- Misc -> Boot -> added HibernateSkipsPicker (Boolean), failsafe value is false.

***_Download table :_***

| OpenCore| Ex Version| New Version| DEBUG VERSION| RELEASE VERSION|
| --- | --- | --- | --- | --- |
|OpenCore | 0.8.6 | 0.8.7 | [OpenCore 0.8.7 DEBUG](https://github.com/acidanthera/OpenCorePkg/releases/download/0.8.7/OpenCore-0.8.7-DEBUG.zip)| [OpenCore 0.8.7 RELEASE](https://github.com/acidanthera/OpenCorePkg/releases/download/0.8.7/OpenCore-0.8.7-RELEASE.zip)

| Kexts| Ex Version| New Version| DEBUG VERSION| RELEASE VERSION|
| --- | --- | --- | --- | --- |
| AppleALC | 1.7.6 | 1.7.7 | [AppleALC 1.7.7 DEBUG](https://github.com/acidanthera/AppleALC/releases/download/1.7.7/AppleALC-1.7.7-DEBUG.zip)| [AppleALC 1.7.7 RELEASE](https://github.com/acidanthera/AppleALC/releases/download/1.7.7/AppleALC-1.7.7-RELEASE.zip)
|HibernationFixup | 1.4.6 | 1.4.7 | [HF 1.4.7 DEBUG](https://github.com/acidanthera/HibernationFixup/releases/download/1.4.7/HibernationFixup-1.4.7-DEBUG.zip)| [HF 1.4.7 RELEASE](https://github.com/acidanthera/HibernationFixup/releases/download/1.4.7/HibernationFixup-1.4.7-RELEASE.zip)
| IntelBluetoothFirmware| 2.2.0 | 2.3.0 BETA | [IBF 2.3.0 BETA DEBUG (From Dortania GitHub)](https://github.com/dortania/build-repo/releases/download/IntelBluetoothFirmware-693f2dc/IntelBluetoothFirmware-2.3.0-DEBUG.zip)| [IBF 2.3.0 BETA RELEASE (From Dortania GitHub again)](https://github.com/dortania/build-repo/releases/download/IntelBluetoothFirmware-693f2dc/IntelBluetoothFirmware-2.3.0-RELEASE.zip)
| VoodooPS2 | 2.3.1 | 2.3.2 | [VoodooPS2 DEBUG](https://github.com/acidanthera/VoodooPS2/releases/download/v2.3.2/VoodooPS2Controller-2.3.2-DEBUG.zip)| [VoodooPS2 RELEASE](https://github.com/acidanthera/VoodooPS2/releases/download/v2.3.2/VoodooPS2Controller-2.3.2-RELEASE.zip)
| WhatEverGreen (WEG)| 1.6.1 | 1.6.2| [WhatEverGreen 1.6.2 DEBUG](https://github.com/acidanthera/WhateverGreen/releases/download/1.6.2/WhateverGreen-1.6.2-DEBUG.zip)| [WhatEverGreen 1.6.2 RELEASE](https://github.com/acidanthera/WhateverGreen/releases/download/1.6.2/WhateverGreen-1.6.2-RELEASE.zip)

Sincerely, UsedDiscord / Magik

⁉️ My Source : Everything comes from the formal creators.

⚠️ ❗  I have not tested anything on the ASUS! I'm posting this just like that but I haven't tested the OpenCore update... nor the Kexts ⚠️  ❗ 

[SOURCE CHANGEMENTS](https://www.reddit.com/r/hackintosh/comments/zem6eh/how_to_opencore_086_087_differences/)

**Comment by Qonfused** [comment]
Will have to investigate pull request permissions.

**Comment by Qonfused** [comment]
Added the [`update-opencore-0.8.7`](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/tree/update-opencore-0.8.7) branch.

**Comment by Qonfused** [comment]
Need to revalidate #8 and #12 after updating Voodoo kexts.
