### ISSUE TITLE
Fix built-in microphone

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#20]

**Comment by danperks** [comment]
FYI I've never had an issue with the built in microphone on the ShieldCK EFI for the UX582

**Comment by Qonfused** [comment]
Yeah it appears the ALC294 codec is also used upstream, which required a custom AppleALC layout (modifying the AppleALC kext). The codec however works, but the microphone works with the use of CodecCommander, which was removed for depreciation (assumed).

Will investigate if a better solution exists, but for now re-adding CodecCommander should resolve this issue.

**Comment by LeongWZ** [comment]
Using ALC294 codec layout 15 on UX431FA. Both audio and microphone work.

Have you tried all possible layouts for ALC294 from this guide? ([https://github.com/acidanthera/AppleALC/wiki/Supported-codecs](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs))

**Comment by Qonfused** [comment]
Another user also reported layout 15 working on the UX481FA model, which would share the same internal layout with the UX434 as the UX431FA.

I was double-checking now to do my due diligence and discovered I had applied an `alc-verbs` arg which had nullified the pin config for layout 15. This ended up being the cause of the issue and fixed the microphone.

@LeongWZ Thanks for the input anyways, it's always worth double-checking.

**Comment by Qonfused** [comment]
Resolved in https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/commit/a162265cc4767df13f7de9ec45e4fbeb9ccbe90f.

**Comment by shiecldk** [comment]
@Qonfused I used to have my own custom AppleALC before but I lost that file, and I need to repatch the audio now. You would need to dump the auto codec from Ubuntu. (You can just boot Ubuntu without installing it)
