### ISSUE TITLE
Fix built-in camera

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#23]
AnyiSightCam UVC driver requires info.plist changes for all instances of `idProduct` and `idVendor` with decimal form of the product and vendor ids. You can find these values for the webcam in system information under USB. May require documentation for potential fixes.

In my case I had `0x56cb` and `0x13d3` for my product and vendor ids.

**Comment by danperks** [comment]
FYI Webcam info on my UX581, in case its the same webcam 

<img width="342" alt="Screenshot 2023-01-03 at 18 48 45" src="https://user-images.githubusercontent.com/49082234/210421926-0f9381cb-55dc-423a-9bb6-6f6602427515.png">

**Comment by Qonfused** [comment]
Yeah, it appears to be the same webcam. It looks like yours is missing its serial number, which can be problematic. Does your webcam work on your machine?

**Comment by danperks** [comment]
Webcam is detected in apps but no signal seems to get through, either a black or blank screen depending on the app.

**Comment by Qonfused** [comment]
Interesting note: when the usb camera is passed through to QEMU or VMware Fusion, the camera does properly function when loaded with the proper drivers.

I've added the AnyiSightCam kext in https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/commit/e0672e87eb7d4d2a78975f29b1ebd285a1323b21, though this assumes PID `0x56cb`; instances of `22219` will need to be replaced with `22251` for product ids under IOKitPersonalities (in the kext Info.plist).

**Comment by Qonfused** [comment]
Reopening as current issue is a regression.

**Comment by shiecldk** [comment]
@Qonfused @danperks Do you reset your BIOS settings and stop using modGRUBShell? I found out modGRUBShell can mess up USB ports on my UX582. Once I stop using modGRUBShell and only set the BIOS settings, I can get the camera and the USB ports to work normally.

I only set these options in BIOS:
- Fast Boot: Disabled
- Secure Boot Control: Disabled
- VT-d: Disabled
- SATA Mode Selection: AHCI
- DVMT Pre-Allocated: 64M

**Comment by Qonfused** [comment]
> @Qonfused @danperks Do you reset your BIOS settings and stop using modGRUBShell? I found out modGRUBShell can mess up USB ports on my UX582. Once I stop using modGRUBShell and only set the BIOS settings, I can get the camera and the USB ports to work normally.

Yes, I have re-flashed my bios since then; my current settings for reference are listed in https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/wiki/Install-Guide-(WIP)

**Comment by Qonfused** [comment]
I don't believe there is a fix for this. Will revisit if more information about the underlying issue is found.

**Comment by Qonfused** [comment]
It's marked as internal here under port 5:
![image](https://github.com/user-attachments/assets/5f03cc2b-535a-4a17-9d7e-ead5eea6a39e)
https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/83efd22fafbbeaf76c5bec7a3fa868ed32c49908/src/Kexts/UTBMap.kext/Contents/Info.plist#L81-L89

Unfortunately there is no driver support in macOS for UVC/IR cameras.

**Comment by shiecldk** [comment]
@Qonfused  Have you checked these?
https://github.com/cobaohieu/ASUS-K55VD-HACKINTOSH/issues/8
https://www.tonymacx86.com/threads/hp-hd-camera-not-working-on-hp-probook-450-g7-uvc-camera.324547/

https://www.perplexity.ai/search/how-to-get-uvc-ir-cameras-on-m-1rJgMFH5R1aUQSAf_Zhv9Q#0

**Comment by Qonfused** [comment]
I have seen the GitHub issue before, but not after Mar 2023. It did mention an [updated version of CameraControl](https://github.com/cobaohieu/CameraControl-macOS-working-on-version-10.15-11.7), but I'm not sure if this still works past Mojave. The main suspicion is that the camera exposure isn't set by default, so the incoming image will always be black.

There aren't any additional wires/controls exposed by the camera, so the only way to control the camera exposure would be through a UVC/IR driver.

![image](https://github.com/user-attachments/assets/ca395c1f-6c90-4937-9ffd-e0033cf3d9c1)
![image](https://github.com/user-attachments/assets/23c7c362-f709-4859-92e3-e30e0a5d4810)

**Comment by wassupsam** [comment]
Hey even i have the same issue am on ventura 
![Screenshot 2024-12-31 at 10 15 48 AM](https://github.com/user-attachments/assets/84956fef-a183-4020-9d74-4a5747d02321)
![Screenshot 2024-12-31 at 10 16 58 AM](https://github.com/user-attachments/assets/30bb5e67-8be6-495e-a1e1-09f3934571ed)
