### ISSUE TITLE
"Unlock with Apple Watch" Support?

### ISSUE THREAD

**Issue by danperks** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#30]
Does the WiFi chip in the Zenbook's support this feature? Not entirely sure what the requirements are for this to work, but I know it doesn't for me using @shiecldk EFI, just gets stuck attempting to unlock then prompts for a password instead.

For reference, the Wi-Fi card appears to be a derivative of [this](https://www.intel.co.uk/content/www/uk/en/products/sku/130293/intel-wifi-6-ax201-gig/specifications.html)

**Comment by Qonfused** [comment]
This appears to require a native broadcom chipset; intel wifi+bluetooth doesn't natively support features like Airdrop or unlock with Apple Watch. You'll notice that some native features have been supported through the [FeatureUnlock](https://github.com/acidanthera/FeatureUnlock) Lilu plugin, but my understanding is that this feature requires a proper biometric device, which these devices lack.

**Comment by Qonfused** [comment]
Will close this issue as 'not planned' for now, at least until the scope of the issue upstream is clearer or after some progress on this front is announced.

**Comment by Qonfused** [comment]
Using a native airport Wi-Fi card is a workaround applicable to the UX581GV, which is probably worth mentioning:
https://dortania.github.io/Wireless-Buyers-Guide/Airport.html#airport-adapters
