### ISSUE TITLE
Add RTS522A microSD reader driver

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#35]
With the addition of SD card device path support in OpenCore 0.8.8, it may become desirable to explore SD card support at boot. The UX481FA/FL models feature a RTS522A PCI express card reader ([cf.](https://linux-hardware.org/?id=pci:10ec-522a-1043-202f)) which requires a driver to be loaded for boot entries to be properly detected and loaded by OpenCore. These drivers can be pulled from the BIOS image, with other models provided by OcBinaryData per this commit: https://github.com/acidanthera/OcBinaryData/commit/4d362e85befcd4493ae8d32c65c728f96eb13eeb.

This is based on information found in https://github.com/acidanthera/bugtracker/issues/1894, concerning the same PCI SD card reader. ~~This will need to be tested on other models (UX581/UX582) as they may feature the same device.~~

**Comment by shiecldk** [comment]
Not sure about UX581, but the UX582 model doesn't have a card reader.

**Comment by Qonfused** [comment]
Looks like they're not present in either model. I saw it was present in the device schematic for the UX581 but that must have been included there in error.
