### ISSUE TITLE
[Wiki] Steps for Beginners

### ISSUE THREAD

**Issue by erkan377** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#41]
### Proposal

I'm a beginner and I don't really understand how to use your configuration, do you have a tutorial or can tell me all the steps to follow to succeed in doing it? THANKS!

**Comment by Qonfused** [comment]
Are you confused with build instructions or with using the EFI? The EFI creation process is already covered by this repository's built EFIs. You can find zipped archives for each release version [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/releases) if you don't want to build the project source.

I haven't yet written an installation guide, though there are resources available for creating a macOS installer + using an EFI in the Dortania guide: https://dortania.github.io/OpenCore-Install-Guide.

This is a rough outline of how you'd setup OpenCore with the linked guide:
* Change these BIOS settings: https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/wiki/Install-Guide-(WIP)
* macOS installer creation: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/#making-the-installer
  * Move the unzipped EFI to your system EFI partition: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-opencore-s-efi-environment
* macOS installation process: https://dortania.github.io/OpenCore-Install-Guide/installation/installation-process.html#installation-process

If you prefer not to modify your system EFI partition, you can also create a new 200 MB fat32 partition on your internal SSD and move the EFI there instead.

**Comment by Qonfused** [comment]
Let me know if you have any specific questions or issues as it also informs me what I should look at covering in a proper installation guide.

**Comment by erkan377** [comment]
do you have a discord?

**Comment by erkan377** [comment]
I'm stuck here can you tell me how to do it? https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos
