### ISSUE TITLE
Add correct SecureBootModel value

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#42]
The correct SecureBootModel key (under Misc > Security) is `j223` for the MacBookPro16,3 SMBIOS.

Some more information here that describes potential issues:
https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel

**Comment by shiecldk** [comment]
Would this be the same for UX582?
