### ISSUE TITLE
[BIOS/UEFI] Disable CFGLock with `ControlMsrE2.efi` tool

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#44]
A good breakdown of how this driver works is explained in an [InsanelyMac Forum post](https://www.insanelymac.com/forum/topic/345492-guide-unlocking-cfg-with-opencore-and-cfglockefi/) by **@miliuco**; the driver scans the BIOS's HiiDatabase for CFG Lock registers, and can set their bits to <kbd>0x00</kbd> to unlock them.

This is primarily needed for power management (required by the kernel and AppleCPUPowerManagement) as it's needed to define the CPU's C-states or idle states.

#### Requires:
* `UEFIShell.efi` - For running commands/drivers interactively.
* `ControlMsrE2.efi`/`CFGLock.efi` - For unlocking CFG Lock (ref: 0xE2 MSR register).

#### Disable:
* https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/0c0443683921b29f1cc92b5c627690fe5d317b88/src/config.yml#L102-L107

**Comment by Qonfused** [comment]
`RU.efi` alternative: https://github.com/dreamwhite/bios-extraction-guide/blob/master/ru.efi.md

**Comment by Qonfused** [comment]
Requires testing on UX581/UX582 firmwares.

**Comment by shiecldk** [comment]
@Qonfused I can test this. How is this different from using modGRUBShell.efi to modify the hidden BIOS settings for CFGLock or using the AppleCpuPmCfgLock and AppleXcpmCfgLock under Kernel -> Quirks in OpenCore config.plist?

**Comment by Qonfused** [comment]
There's two different approaches here, though in short it isn't functionally different from the `modGRUBShell.efi` approach but is significantly easier for the end-user.

For proper CPU power management, macOS needs to be able to write the E2 MSR (`PKG_CST_CONFIG_CONTROL`) to define the C-states (or power-saving states) of the CPU. Otherwise this will cause a kernel panic since XNU expects to be able to write there. By default, ASUS locks writes to the whole MSR E2 region, though this can be unlocked with CFG Lock in the BIOS (or using `modGRUBShell.efi` / `ControlMsrE2.efi`).

The alternative approach is to forfeit power management and patch out XNU's writes to this MSR region with `AppleCpuPmCfgLock` and `AppleXcpmCfgLock`. It's best used as a last-resort for when no CFG Lock setting is provided in firmware since it otherwise needlessly borks native power management. You can also no longer do this on macOS 13+ as the CPU PM kext was dropped (unless you load and patch a legacy version).

**Comment by shiecldk** [comment]
I see. So the best option would be using ControlMsrE2.efi and CFGLock.efi? I see the insanelymac post says that they are already included in OpenCore?

**Comment by Qonfused** [comment]
ControlMsrE2 is what it's named in the OpenCore release package. They're the easiest (automated) approach, though the fallback would still be to use the GRUB shell. If compatible, it should be the preferred approach.
