### ISSUE TITLE
Dropped support for NVMeFix in macOS 14

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#45]
> --- @vit9696: https://github.com/acidanthera/NVMeFix/pull/7#issuecomment-1578275605 ---
> Updating NVMeFix to macOS 14 will require substantial code changes. I would say current NVMeFix is already pretty much discontinued and needs fixes even for macOS 13. We will probably not release an update for it with macOS 14 support.

**Comment by ExtremeXT** [comment]
https://github.com/acidanthera/NVMeFix/commit/af93868c86da3a0a4be6419a4949e5f4437ba4eb

**Comment by shiecldk** [comment]
@Qonfused it looks like they have updated NVMeFix for macOS 14:
https://github.com/acidanthera/NVMeFix/releases
