### ISSUE TITLE
[Bug]: Thunderbolt not working with eGPU and system info miss thunderbolt description

### ISSUE THREAD

**Issue by shiecldk** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#57]
### Zenbook Duo Variant

i5/i7 UX481FL (with Nvidia MX250), i5/i7 UX481FA (without Nvidia MX250)

### OpenCore Version

1.0.2 Release

### Current Behavior

The current thunderbolt implementation does not show thunderbolt in macOS system description, and eGPU is not working possibly due to GPIO3 Force Power is not enabled. (We need to check how to enable this in BIOS or SSDT.) However, it looks like we need to dump the Setup.txt from Setup.efi in BIOS with ifrextract to check the hidden BIOS option for thunderbolt.

These are the resources related to solving this issue:
https://github.com/utopia-team/Thunderbolt
https://www.tonymacx86.com/threads/thunderbolt-3-modified-firmware-custom-ssdt-discussion.293279/
ttps://github.com/seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh/blob/main/README_en.md
https://github.com/osy/ThunderboltReset/blob/master/PatchingACPI.md

### Expected Behavior

macOS system description should show thunderbolt device. And eGPU should work with thunderbolt port when it's attached to the thunderbolt port.

**Comment by Qonfused** [comment]
Unlike most other midrange to high-end Comet Lake laptops, the UX481 doesn't have any Thunderbolt 3 ports; the USB-C port is 3.1 Gen 2.
