### ISSUE TITLE
Document Original Repo's ACPI patches

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#7]
A basic breakdown of each file is given below:

File | Required | Description
--- | --- | ---
SSDT-ALC294.aml | Yes
SSDT-ASUSFN.aml | Yes
SSDT-AsusSMC.aml | Yes
SSDT-AWAC | Yes
SSDT-DDGPU.aml | No | Disables dGPU through a SSDT
SSDT-DTGP.aml | No | Handles macOS specific behavior when calling the _DSM method to limit visible device properties ([please don't use](https://www.tonymacx86.com/threads/modify-dsdt-for-lpcb-ionamematch.210070/#post-1395509))
SSDT-EC-USBX-LAPTOP.aml | Yes
SSDT-ELAN-POLLING.aml | Yes
SSDT-GPRW.aml | Yes | Instant wake patch (e.g. USB or power state changes wakes device from sleep).
SSDT-OC-XOSI.aml | Yes
SSDT-Plug.aml | Yes | Enables XCPM (XNU CPU power management) to manage the CPU's power management.
SSDT-PNLFCFL.aml | Yes | Handles backlight control of main display.
SSDT-RHUB.aml | Yes | Disables USB RHUB to avoid issues booting macOS.
SSDT-TB3.aml | Yes | Related to Thunderbolt 3?
SSDT-PTS.aml | Yes | Overrides '_PTS' to wake then put dGPU to sleep to prevent black screen on wake.
SSDT-DMAC.aml/SSDT-MEM2.aml | No | Allows for more 'mac-like' memory behavior (see [this post](https://www.tonymacx86.com/threads/x299-big-sur-support.302143/page-35))
SSDT-IMEI.aml | No | Creates new IMEI device to allow applying device-ids (required if no IMEI device with any name is present in ACPI tables).
SSDT-PMCR.aml/SSDT-PPMC.aml | No | Adds an undocumented & missing PMCR device to enable native NVRAM for non-native NVRAM.
SSDT-SBUS-MCHC.aml | No | Fixes AppleSMBus support (e.g. CPU temp, fans, low bandwidth PCI, memory reporting, etc).
SSDT-XSPI.aml | No | ?
SSDT-ETPD.aml | No | Enables GPI0 interrupts (for ELAN trackpad polling)

**Comment by Qonfused** [comment]
It seems that an ambient light sensor is needed for backlight to function (since macOS 15 Catalina). The SMCLightSensor kext handles reporting actual SMC values or dummy values; if there is no ambient light sensor I'd have to remove the ALS0 kext (since there is no physical device to define).

**Comment by Qonfused** [comment]
![Screen Shot 2022-11-22 at 3 45 55 PM](https://user-images.githubusercontent.com/32466081/203427599-c6bb4b36-7021-46fc-b265-28f5dffbaa37.png)
![Screen Shot 2022-11-22 at 3 40 54 PM](https://user-images.githubusercontent.com/32466081/203426776-8d011587-dcb8-40ce-ac45-32ac5cea1cbd.png)

**Comment by Qonfused** [comment]
Another note: SSDT-PLUG is no longer needed on Monterey 12.3+

**Comment by Qonfused** [comment]
Unsure of the necessity of these ACPI quirks (including the IMEI SSDT):
![image](https://user-images.githubusercontent.com/32466081/203481412-164e8986-6501-49a2-9d63-b84ba5a8519e.png)

**Comment by Qonfused** [comment]
IMEI SSDT is not necessary:
![Screen Shot 2022-11-23 at 12 06 22 AM](https://user-images.githubusercontent.com/32466081/203481927-6f921114-1f43-4886-bec2-a87962a401e1.png)

**Comment by Qonfused** [comment]
More info in https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html.

**Comment by Qonfused** [comment]
May also need to investigate whether or not this is still needed for the trackpad:
![image](https://user-images.githubusercontent.com/32466081/203483412-d285b877-775a-4f41-beae-eb34c9e5739b.png)

**Comment by Qonfused** [comment]
Posting this resource for later documentation:
https://5t33z0.gitbook.io/oc-litte-translated/oc-little/acpi/acpi-basics

**Comment by Qonfused** [comment]
Will only have to document this repo's ACPI.

**Comment by Qonfused** [comment]
Fix issue status

**Comment by shiecldk** [comment]
It seems that without SSDT-PTS.aml, on UX582, the shutdown would fail sometimes. But this problem only existed a long time ago when I initially pushed the OC EFI to GitHub; not sure if it has been fixed by other patches.

**Comment by shiecldk** [comment]
Do you have a working NVRAM on your model?

**Comment by Qonfused** [comment]
> SSDT-DTGP.aml is required to be used with SSDT-TB3.aml since the Device (UPSB) in SSDT-TB3.aml is calling the _DSM method. (for UX582 model)

My initial comments on DTGP were misled; the DTGP method may be necessary in order to inject device properties during earlier parts of macOS's initialization. I'd see if you can use device property injection instead, but it may not reliably inject w/o using DTGP.

I'm not familiar with the thunderbolt SSDTs/patches, though I have a z490i system with thunderbolt 3 I can test with. It may be more involved on a laptop with multiple thunderbolt controllers.

> It seems that without SSDT-PTS.aml, on UX582, the shutdown or restart on macOS would fail sometimes. But this problem only existed a long time ago when I initially pushed the OC EFI to GitHub; not sure if it has been fixed by other patches.

I'd still verify whether you still need this SSDT All this SSDT seems to do is power down USB controller(s), which can conflict with shutdown/restart (possibly sleep as well).

> Do you have a working NVRAM on your model? (saves the boot disk in OpenCore)

NVRAM does work natively on my model. I was unsure when I was first investigating it, but macOS does correctly read the `csr-active-config` NVRAM variable, and custom boot entry creation was tested as working.
